<a href="https://colab.research.google.com/github/sathwikbhat7/Pytorch-Practice/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

default data type of float32.

More suitable for deep learning than a numpy array.

In [1]:
import torch
import numpy as np

**LISTS**

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY ARRAYS**


In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.84879293, 0.48032034, 0.57812993, 0.67853018],
       [0.63963414, 0.59501834, 0.85499822, 0.46164775],
       [0.5460343 , 0.02590531, 0.64325693, 0.29479075]])

In [5]:
np1.dtype

dtype('float64')

**TENSORS**

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 2.0478, -0.4339,  1.0520,  2.2241],
        [-0.3771, -0.1068,  0.8502, -0.0254],
        [-0.3052,  1.3761, -1.1900,  0.2532]])

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor


tensor([[0.8488, 0.4803, 0.5781, 0.6785],
        [0.6396, 0.5950, 0.8550, 0.4616],
        [0.5460, 0.0259, 0.6433, 0.2948]], dtype=torch.float64)